### ISSUE TITLE
Trying to read report

### ISSUE THREAD

**Issue by Asken** [mikeobrien/HidLibrary#123]
```
var devices = HidLibrary.HidDevices.Enumerate(1848);
device = devices.FirstOrDefault();
device.OpenDevice();
device.ReadReport(ReadReportCallback);
```

Gives me `System.PlatformNotSupportedException: 'Operation is not supported on this platform.'`

I'm on win 10 running .Net 5

**Comment by Asken** [comment]
I used the source and then it's something else :)

**Comment by olegtar83** [comment]
> I used the source and then it's something else :)

Hi, i got the same issue, can you share how you fixed it?

**Comment by Asken** [comment]
I hardly remember but I think I used the source from git rather than the nuget package

**Comment by olegtar83** [comment]
Nah.. it didn`t worked.. do you rewrite the BeginInvoke() method, could you check?
