### ISSUE TITLE
USB HID hangs on Read() 

### ISSUE THREAD

**Issue by hassa687** [mikeobrien/HidLibrary#17]
Hi Mike,

I am trying to connect to a digital scale in c# using your library. For some reason its hangs on Read, appreciate any help please.

Somebody else also ran into the same issue here:
http://stackoverflow.com/questions/5596531/c-sharp-net-get-scale-weight-usb-windows-7-64-bit

Posted it as a question here
http://stackoverflow.com/questions/10178375/usb-hid-hangs-on-read-in-c-sharp

**Comment by itsudhiryadav** [comment]
Hi @hassanjahmed , Where is the Data class where you create an instance of it inside the method OnReport? Thanks in advance!
