### ISSUE TITLE
Is this library maintained any more?

### ISSUE THREAD

**Issue by voltagex** [mikeobrien/HidLibrary#57]
Hi,
Is this being maintained any more? Completely understand if it isn't - but which fork should users move on to?

**Comment by amullins83** [comment]
Yes. As you can see from the commit history, we converted to async-await syntax early this year, and then Mike converted build tools to use Gulp this summer.

**Comment by voltagex** [comment]
Cool, thanks for the response

**Comment by mikeobrien** [comment]
I haven't been very active but folks like @amullins83 have. There are also some other options out there for c#: http://stackoverflow.com/questions/2803890/net-api-for-hid-usb
