### ISSUE TITLE
ReadProduct fails to return data

### ISSUE THREAD

**Issue by 63degrees** [mikeobrien/HidLibrary#62]
The underlying code in NativeMethod.cs HidD_GetProductString needs a larger buffer.
It is set at 64 bytes. MS API states 126 wide (see below). A wide character is a 2-byte multilingual character code.  I changed the ReadProcduct byte array to 252 and it worked for me.

https://msdn.microsoft.com/en-us/library/ff539681.aspx

The maximum possible number of characters in an embedded string is device specific. For USB devices, the maximum string length is **126 wide characters** (not including the terminating NULL character).

If the buffer is not large enough to return the entire NULL-terminated embedded string, the routine returns nothing in the buffer.

**Comment by amullins83** [comment]
Submit a pull request with your fix. I would make the buffer 254 bytes wide so there is space for the terminating null.

**Comment by 63degrees** [comment]
Agree with the byte buffer 254 length.
