### ISSUE TITLE
CardInserted event

### ISSUE THREAD

**Issue by bartbor** [mikeobrien/HidLibrary#68]
Is there any way to get an event when de card is removed from the card reader?
What I am looking for is to create a 'CardStatusChanged' event with 'Inserted' and 'Removed' statusses.

I have been looking through the code.  The events 'Connected' and 'Removed' seem to apply to the reader itself.

thx

**Comment by amullins83** [comment]
That implementation depends on the specifics of your device. The intent of this library is to be generic. You will need to write the code to detect card insertion and removal.
