### ISSUE TITLE
HidDevice.Description doesn't support not english letters

### ISSUE THREAD

**Issue by alexwlpr** [mikeobrien/HidLibrary#72]
Hello. I'm using library from NuGet, version 3.2.37.
I get devices via HidDevices.Enumerate(). After it i get each device, read Description property and get somethink like what:
![ss](https://cloud.githubusercontent.com/assets/3435963/20360057/6202ca3a-ac43-11e6-9922-348cb17e3a5b.jpg)
Windows 8.1 x64, Russian

**Comment by waltzofwoe** [comment]
File NativeMethods.cs 
Line 191
Change ``
