### ISSUE TITLE
NuGet package signing

### ISSUE THREAD

**Issue by jdouglas-nz** [mikeobrien/HidLibrary#87]
Hi There,

could I please ask that the package distributed on NuGet is signed so that it can be used in a 'signed' environment without resigning ? 

Thanks!

**Comment by mikeobrien** [comment]
Sorry, I know its a pain for a few but I don't want to sign assemblies because that will be a pain for the majority. There are [some options out there](https://www.nuget.org/packages/strongnamer) however to automatically sign unsigned assemblies, so shouldn't be too hard implement.
